"""
Django settings for powerbuilder_app project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
env = environ.Env(
    DEBUG=(bool, False)
)

environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# All API keys are optional at startup so the app can boot in offline / demo
# scenarios. Code that uses them must handle missing values explicitly
# (the researcher's local-corpus fallback is the canonical example).
OPENAI_API_KEY = env('OPENAI_API_KEY', default='')
GOOGLE_API_KEY = env('GOOGLE_API_KEY', default='')
LLAMA_CLOUD_API_KEY = env('LLAMA_CLOUD_API_KEY', default='')
PINECONE_API_KEY = env('PINECONE_API_KEY', default='')
OPENAI_PINECONE_INDEX_NAME = env('OPENAI_PINECONE_INDEX_NAME', default='')
GOOGLEAI_PINECONE_INDEX_NAME = env('GOOGLEAI_PINECONE_INDEX_NAME', default='')

# ---------------------------------------------------------------------------
# Production / demo flags
# ---------------------------------------------------------------------------

# DEBUG defaults to False (production-safe). Set DEBUG=True in .env for local
# development. The previous hardcoded `DEBUG = True` line below the env read
# was a footgun that could ship to production by accident, removed.
DEBUG = env.bool('DEBUG', default=False)

# DEMO_MODE: when true, the app behaves predictably for live audiences.
# - Random sampling uses a fixed seed (see chat/utils/random_seed.py)
# - File upload UI is hidden (corpus + synthetic voterfile are pre-loaded)
# - Admin link is not exposed in the navigation
# Independent of DEBUG: you can run DEMO_MODE=true with DEBUG=false in front
# of an audience on a hardened deployment.
DEMO_MODE = env.bool('DEMO_MODE', default=False)

# Deterministic seed used when DEMO_MODE is on. Documented here so anyone
# reading the settings knows where the magic number comes from.
DEMO_RANDOM_SEED = env.int('DEMO_RANDOM_SEED', default=2026)

# Hosts allowed to serve the app. In dev we accept localhost; in production
# this must be a comma-separated list set via the ALLOWED_HOSTS env var.
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# Move the Django admin off the default /admin/ path so attackers can't find
# it with a one-second scan. Override per-environment via ADMIN_URL_PATH.
# The trailing slash is added automatically if missing.
_admin_path = env('ADMIN_URL_PATH', default='admin')
ADMIN_URL_PATH = _admin_path.strip('/') + '/'

# When DEBUG is off, turn on the production security headers Django ships
# with. These are no-ops in dev (DEBUG=True), so it is safe to set them here
# unconditionally and let the Django security middleware decide.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=31536000)  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat',
    'django_htmx',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves collected static files directly from the WSGI process.
    # Must come immediately after SecurityMiddleware (per WhiteNoise docs) and
    # before any middleware that produces responses, so static asset requests
    # short-circuit the rest of the stack. No-op in dev when DEBUG=True —
    # Django's runserver still serves static files itself.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # LocaleMiddleware must come AFTER SessionMiddleware (so it can read the
    # session) and BEFORE CommonMiddleware (so URL resolution sees the locale).
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    # Blocks unauthenticated POST requests to query endpoints with HTTP 401
    'chat.middleware.QueryAuthMiddleware',
]

# Auth redirects
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/chat/'
LOGOUT_REDIRECT_URL = '/login/'

ROOT_URLCONF = 'powerbuilder_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Exposes DEMO_MODE to every template so we can hide the
                # file upload UI and other admin affordances during a live demo.
                'chat.context_processors.demo_flags',
                # i18n context processor exposes LANGUAGES and LANGUAGE_CODE
                # to every template (Milestone Q).
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'powerbuilder_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en'

# Languages we ship UI translations for. Spanish and Vietnamese reflect the
# two largest non-English home languages in Gwinnett County (GA-07). Native
# speakers should review the .po files before any production rollout.
from django.utils.translation import gettext_lazy as _

LANGUAGES = [
    ('en', _('English')),
    ('es', _('Espa\u00f1ol')),
    ('vi', _('Ti\u1ebfng Vi\u1ec7t')),
]

# Where Django looks for compiled .mo files at runtime.
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'America/New_York'

USE_I18N = True
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Compressed + manifest hashing for production static serving via WhiteNoise.
# Each file gets a content-hash suffix so we can serve them with far-future
# Cache-Control headers without worrying about stale assets after a deploy.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
