# powerbuilder/chat/utils/cook_client.py
"""
CookPoliticalClient — Cook Political Report ratings from a static JSON file.

The pre-built file data/cook_ratings.json is generated by calling
refresh_from_api() and ships with the codebase. All lookup methods read from
that file; no live API calls happen during normal pipeline operation.
Call refresh_from_api() manually when ratings change.

Static file schema
------------------
{
    "fetched_at": "<ISO timestamp>",
    "ratings": {
        "house":         [{ID, Title, State, District, Incumbent,
                           Cook_PVI, Rating, Cycle, Rating_date}, ...],
        "senate":        [{Title, State, Incumbent, Rating}, ...],
        "governor":      [{Title, State, Incumbent, Rating}, ...],
        "presidential":  [{Title, State, Electoral_votes, Rating,
                           Cycle, Rating_date}, ...]
    }
}

Returned dict schema
--------------------
{
    "cook_pvi":    "R+5" | "D+3" | "EVEN" | None,
    "race_rating": "Lean R" | "Likely D" | "Toss-up" | None,
    "incumbent":   "Rep. Jane Doe (R)" | None,
    "cycle":       2026 | None,
    "rating_date": "2025-03-15" | None,
    "is_flip":     True | False,   # True when R incumbent (D flip opportunity)
    "source":      "static" | "refresh" | None,
}

None values mean Cook data was not available (file absent or district not covered).
"""

import base64
import json
import logging
import os
import time
from datetime import datetime
from typing import Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

STATIC_RATINGS_PATH = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "../../data/cook_ratings.json")
)
BASE_URL = "https://cookpolitical.com/api/race/"

# Normalise Cook's raw rating strings to consistent short labels.
RATING_MAP = {
    "safe democrat":     "Safe D",
    "likely democrat":   "Likely D",
    "lean democrat":     "Lean D",
    "toss-up":           "Toss-up",
    "toss up":           "Toss-up",
    "lean republican":   "Lean R",
    "likely republican": "Likely R",
    "safe republican":   "Safe R",
}

# Keywords that identify a competitive race (not Safe/Solid).
_COMPETITIVE_KW = ("toss", "lean", "likely")


# ---------------------------------------------------------------------------
# Null result helper (module-level so callers can import it directly)
# ---------------------------------------------------------------------------

def _null_result(source: Optional[str] = None) -> dict:
    return {
        "cook_pvi":    None,
        "race_rating": None,
        "incumbent":   None,
        "cycle":       None,
        "rating_date": None,
        "is_flip":     False,
        "source":      source,
    }


# ---------------------------------------------------------------------------
# Client
# ---------------------------------------------------------------------------

class CookPoliticalClient:
    """
    Reads Cook Political Report ratings from the pre-built static JSON file
    data/cook_ratings.json.

    All lookup methods return _null_result() gracefully when the file is absent,
    so callers never have to handle exceptions and the pipeline continues without
    Cook data.

    Call refresh_from_api() to re-fetch from the live API when ratings change.
    Credentials (COOK_EMAIL, COOK_PASSWORD) are only required for that call.
    """

    def __init__(self):
        self.email      = os.environ.get("COOK_EMAIL", "").strip()
        self.password   = os.environ.get("COOK_PASSWORD", "").strip()
        self._has_creds = bool(self.email and self.password)

        if self._has_creds:
            raw = f"{self.email}:{self.password}".encode()
            self._auth_header = "Basic " + base64.b64encode(raw).decode()
        else:
            self._auth_header = None

        self._static_ratings: dict = self._load_static_ratings()

    # ------------------------------------------------------------------
    # Static file loader
    # ------------------------------------------------------------------

    def _load_static_ratings(self) -> dict:
        """Load and return the pre-built static ratings JSON."""
        try:
            with open(STATIC_RATINGS_PATH) as f:
                data = json.load(f)
            total = sum(len(v) for v in data.get("ratings", {}).values() if isinstance(v, list))
            logger.debug(
                "CookClient: loaded %d ratings (fetched_at=%s)",
                total, data.get("fetched_at", "unknown"),
            )
            return data
        except FileNotFoundError:
            logger.info(
                "CookClient: static ratings file not found at %s. "
                "Run CookPoliticalClient().refresh_from_api() to create it.",
                STATIC_RATINGS_PATH,
            )
            return {}
        except json.JSONDecodeError as e:
            logger.warning("CookClient: static ratings parse error — %s", e)
            return {}

    def _ratings(self, category: str) -> list:
        """Return the record list for a category (house/senate/governor/presidential)."""
        return self._static_ratings.get("ratings", {}).get(category) or []

    # ------------------------------------------------------------------
    # High-level list accessors
    # ------------------------------------------------------------------

    def get_house_ratings(self) -> list:
        """All house records from the static file."""
        return self._ratings("house")

    def get_senate_ratings(self) -> list:
        """All senate records from the static file."""
        return self._ratings("senate")

    def get_governor_ratings(self) -> list:
        """All governor records from the static file."""
        return self._ratings("governor")

    def get_presidential_ratings(self) -> list:
        """All presidential records from the static file."""
        return self._ratings("presidential")

    # ------------------------------------------------------------------
    # District-level lookups
    # ------------------------------------------------------------------

    def get_district_rating(self, state_fips: str, district_num: int) -> dict:
        """
        Return the Cook rating for a U.S. House district.

        Parameters
        ----------
        state_fips   : zero-padded 2-char FIPS code, e.g. '04' for Arizona
        district_num : 1-based integer district number

        Matches the District field in the static file, which is formatted as
        '{ABBR}-{NN}', e.g. state_fips='04', district_num=6 → 'AZ-06'.
        Falls back to the un-padded form ('AZ-6') if the padded form is absent.
        """
        abbr = self._FIPS_TO_ABBR.get(str(state_fips).zfill(2), "")
        if not abbr:
            return _null_result()

        padded   = f"{abbr}-{int(district_num):02d}"
        unpadded = f"{abbr}-{int(district_num)}"

        for record in self._ratings("house"):
            dist = str(record.get("District", "")).strip().upper()
            if dist in (padded, unpadded):
                return self._normalise_record(record)

        return _null_result()

    def get_senate_rating(self, state_name: str) -> dict:
        """
        Return the Cook rating for the U.S. Senate race in a state.

        Parameters
        ----------
        state_name : full state name or 2-char abbreviation
        """
        abbr = self._normalize_state_abbr(state_name)
        for record in self._ratings("senate"):
            if str(record.get("State", "")).strip().upper() == abbr:
                return self._normalise_record(record)
        return _null_result()

    def get_governor_rating(self, state_name: str) -> dict:
        """
        Return the Cook rating for the Governor race in a state.

        Parameters
        ----------
        state_name : full state name or 2-char abbreviation
        """
        abbr = self._normalize_state_abbr(state_name)
        for record in self._ratings("governor"):
            if str(record.get("State", "")).strip().upper() == abbr:
                return self._normalise_record(record)
        return _null_result()

    def get_all_competitive(self) -> list:
        """
        Return all records rated Toss-up, Lean D, Lean R, Likely D, or Likely R
        across house, senate, governor, and presidential categories.
        Excludes Safe D and Safe R entries.

        Each item is the raw record dict merged with the normalised fields and
        a '_category' key indicating which endpoint the record came from.
        """
        results = []
        for category, records in (self._static_ratings.get("ratings") or {}).items():
            for record in (records or []):
                rating_lower = str(record.get("Rating", "")).lower()
                if any(kw in rating_lower for kw in _COMPETITIVE_KW):
                    results.append({
                        **record,
                        "_category": category,
                        **self._normalise_record(record),
                    })
        return results

    def get_ratings_for_state(self, state_name: str) -> dict:
        """
        Return all house, senate, and governor records for a state, normalised.

        Parameters
        ----------
        state_name : full state name or 2-char abbreviation

        Returns
        -------
        {"house": [...], "senate": [...], "governor": [...]}
        """
        abbr = self._normalize_state_abbr(state_name)

        house = [
            self._normalise_record(r)
            for r in self._ratings("house")
            if self._district_state_abbr(str(r.get("District", ""))) == abbr
        ]
        senate = [
            self._normalise_record(r)
            for r in self._ratings("senate")
            if str(r.get("State", "")).strip().upper() == abbr
        ]
        governor = [
            self._normalise_record(r)
            for r in self._ratings("governor")
            if str(r.get("State", "")).strip().upper() == abbr
        ]

        return {"house": house, "senate": senate, "governor": governor}

    # ------------------------------------------------------------------
    # API refresh
    # ------------------------------------------------------------------

    def refresh_from_api(self) -> bool:
        """
        Re-fetch all four endpoints from the Cook Political API and overwrite
        data/cook_ratings.json.

        Requires COOK_EMAIL and COOK_PASSWORD environment variables.
        Returns True on success, False on failure.
        This is the only method that makes live HTTP calls.
        """
        if not self._has_creds:
            logger.error(
                "CookClient: refresh_from_api requires COOK_EMAIL and COOK_PASSWORD."
            )
            return False

        try:
            import requests as _requests
        except ImportError:
            logger.error("CookClient: 'requests' package not installed.")
            return False

        endpoints = ["house", "senate", "governor", "presidential"]
        ratings: dict = {}

        for endpoint in endpoints:
            try:
                time.sleep(0.5)     # polite rate-limit between requests
                resp = _requests.get(
                    BASE_URL + endpoint,
                    headers={
                        "Authorization": self._auth_header,
                        "Accept":        "application/json",
                    },
                    timeout=30,
                )
                resp.raise_for_status()
                data = resp.json()
                if isinstance(data, list):
                    ratings[endpoint] = data
                    logger.info("CookClient: fetched %d %s records", len(data), endpoint)
                else:
                    logger.warning("CookClient: /%s returned non-list response", endpoint)
                    ratings[endpoint] = []
            except Exception as e:
                logger.warning("CookClient: /%s request failed — %s", endpoint, e)
                ratings[endpoint] = []

        payload = {
            "fetched_at": datetime.now().isoformat(),
            "ratings":    ratings,
        }

        try:
            os.makedirs(os.path.dirname(STATIC_RATINGS_PATH), exist_ok=True)
            with open(STATIC_RATINGS_PATH, "w") as f:
                json.dump(payload, f, indent=2)
            self._static_ratings = payload
            total = sum(len(v) for v in ratings.values())
            logger.info(
                "CookClient: saved %d total ratings to %s", total, STATIC_RATINGS_PATH
            )
            return True
        except OSError as e:
            logger.error("CookClient: could not write static ratings — %s", e)
            return False

    # ------------------------------------------------------------------
    # Legacy fetch() — backward compatibility
    # ------------------------------------------------------------------

    def fetch(
        self,
        district_type: str,
        district_id: str,
        state_fips: str,
        cycle: int = 2026,
    ) -> dict:
        """
        Legacy entry point kept for backward compatibility.
        Prefer get_district_rating() / get_senate_rating() / get_governor_rating()
        for new callers.
        """
        if district_type in ("state_house", "state_senate"):
            return _null_result()
        if district_type == "senate":
            return self.get_senate_rating(self._fips_to_abbr(state_fips))
        if district_type == "governor":
            return self.get_governor_rating(self._fips_to_abbr(state_fips))
        # congressional
        try:
            dist_num = int(district_id[len(state_fips):].lstrip("0") or "1")
        except (ValueError, IndexError):
            dist_num = 1
        return self.get_district_rating(state_fips, dist_num)

    # ------------------------------------------------------------------
    # Normalisation helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _normalise_record(record: dict, source: str = "static") -> dict:
        """Convert a raw API/static record to the standard returned-dict schema."""
        raw_rating    = str(record.get("Rating", "")).lower().strip()
        incumbent_str = str(record.get("Incumbent") or record.get("incumbent") or "")
        # is_flip: incumbent is Republican → this seat is a D flip opportunity.
        is_flip = "(R)" in incumbent_str or " R)" in incumbent_str
        return {
            "cook_pvi":    record.get("Cook_PVI") or record.get("cook_pvi"),
            "race_rating": RATING_MAP.get(raw_rating) or record.get("Rating") or None,
            "incumbent":   incumbent_str or None,
            "cycle":       record.get("Cycle") or record.get("cycle") or 2026,
            "rating_date": record.get("Rating_date") or record.get("rating_date"),
            "is_flip":     is_flip,
            "source":      source,
        }

    @staticmethod
    def _district_state_abbr(district_str: str) -> str:
        """Extract state abbreviation from a 'AZ-06'-style district string → 'AZ'."""
        parts = district_str.strip().upper().split("-", 1)
        return parts[0] if len(parts) == 2 else ""

    @staticmethod
    def _normalize_state_abbr(state: str) -> str:
        """Convert a full state name or 2-char abbreviation to an uppercase 2-char abbr."""
        state = state.strip()
        if len(state) == 2:
            return state.upper()
        _NAME_TO_FIPS = {
            "alabama": "01", "alaska": "02", "arizona": "04", "arkansas": "05",
            "california": "06", "colorado": "08", "connecticut": "09", "delaware": "10",
            "district of columbia": "11", "florida": "12", "georgia": "13", "hawaii": "15",
            "idaho": "16", "illinois": "17", "indiana": "18", "iowa": "19", "kansas": "20",
            "kentucky": "21", "louisiana": "22", "maine": "23", "maryland": "24",
            "massachusetts": "25", "michigan": "26", "minnesota": "27", "mississippi": "28",
            "missouri": "29", "montana": "30", "nebraska": "31", "nevada": "32",
            "new hampshire": "33", "new jersey": "34", "new mexico": "35", "new york": "36",
            "north carolina": "37", "north dakota": "38", "ohio": "39", "oklahoma": "40",
            "oregon": "41", "pennsylvania": "42", "rhode island": "44", "south carolina": "45",
            "south dakota": "46", "tennessee": "47", "texas": "48", "utah": "49",
            "vermont": "50", "virginia": "51", "washington": "53", "west virginia": "54",
            "wisconsin": "55", "wyoming": "56",
        }
        fips = _NAME_TO_FIPS.get(state.lower())
        if fips:
            return CookPoliticalClient._FIPS_TO_ABBR.get(fips, state[:2].upper())
        return state[:2].upper()

    # FIPS → 2-char state abbreviation. Used internally and by election_results.py.
    _FIPS_TO_ABBR = {
        "01": "AL", "02": "AK", "04": "AZ", "05": "AR", "06": "CA",
        "08": "CO", "09": "CT", "10": "DE", "11": "DC", "12": "FL",
        "13": "GA", "15": "HI", "16": "ID", "17": "IL", "18": "IN",
        "19": "IA", "20": "KS", "21": "KY", "22": "LA", "23": "ME",
        "24": "MD", "25": "MA", "26": "MI", "27": "MN", "28": "MS",
        "29": "MO", "30": "MT", "31": "NE", "32": "NV", "33": "NH",
        "34": "NJ", "35": "NM", "36": "NY", "37": "NC", "38": "ND",
        "39": "OH", "40": "OK", "41": "OR", "42": "PA", "44": "RI",
        "45": "SC", "46": "SD", "47": "TN", "48": "TX", "49": "UT",
        "50": "VT", "51": "VA", "53": "WA", "54": "WV", "55": "WI",
        "56": "WY",
    }

    def _fips_to_abbr(self, fips: str) -> str:
        return self._FIPS_TO_ABBR.get(str(fips).zfill(2), fips)
